INSERT INTO product
(name, description, brand, price, category, release_date, available, quantity, image)
VALUES
    ('RTX 5070',
     'High-performance NVIDIA graphics card for gaming and creative workloads.',
     'NVIDIA',
     649.99,
     'GPU',
     '2025-04-15',
     TRUE,
     25,
     'https://example.com/images/rtx-5070.jpg'),

    ('Ryzen 7 9800X3D',
     'High-end AMD processor designed for exceptional gaming performance.',
     'AMD',
     479.99,
     'CPU',
     '2024-11-07',
     TRUE,
     12,
     'https://example.com/images/ryzen-7-9800x3d.jpg'),

    ('Core i7-14700K',
     'Powerful Intel desktop processor with high core and thread count.',
     'Intel',
     389.99,
     'CPU',
     '2023-10-17',
     TRUE,
     18,
     'https://example.com/images/i7-14700k.jpg'),

    ('Samsung Odyssey G7',
     '32-inch QHD gaming monitor with a high refresh rate and curved display.',
     'Samsung',
     599.99,
     'Monitor',
     '2024-02-20',
     TRUE,
     8,
     'https://example.com/images/odyssey-g7.jpg'),

    ('Logitech G Pro X Superlight 2',
     'Lightweight wireless gaming mouse designed for competitive gaming.',
     'Logitech',
     159.99,
     'Mouse',
     '2023-09-05',
     TRUE,
     35,
     'https://example.com/images/g-pro-x-superlight-2.jpg');